import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Practice",
  description: "Generated by sk",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const response = await fetch(`http://localhost:9999/topics`);
  const topics = await response.json();

  return (
    <html>
      <body>
        <Link href={"/"}>web</Link>
        <li>
          <Link href={"/read/1"}>리드1</Link>
        </li>
        <li>
          <Link href={"/read/2"}>리드2</Link>
        </li>
        <ol>
          {topics.map((topic: any) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>

        {children}
        <li>
          <Link href={"/create"}>create</Link>
        </li>
        <li>
          <Link href={"/update/1"}>update</Link>
        </li>
        <li>
          <input type="button" value="delete"></input>
        </li>
      </body>
    </html>
  );
}
