import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Practice",
  description: "Generated by sk",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Link href={"/"}>web</Link>
        <li>
          <Link href={"/read/1"}>리드1</Link>
        </li>
        <li>
          <Link href={"/read/2"}>리드2</Link>
        </li>

        {children}
        <li>
          <Link href={"/create"}>create</Link>
        </li>
        <li>
          <Link href={"/update/1"}>update</Link>
        </li>
        <li>
          <input type="button" value="delete"></input>
        </li>
      </body>
    </html>
  );
}
